-- F&I: ficha cadastral completa (PF/PJ) — só adiciona colunas opcionais.
ALTER TABLE "finance_proponents"
  ADD COLUMN IF NOT EXISTS "sexo" TEXT,
  ADD COLUMN IF NOT EXISTS "rgUf" TEXT,
  ADD COLUMN IF NOT EXISTS "rgDataEmissao" TIMESTAMP(3),
  ADD COLUMN IF NOT EXISTS "naturalidadeUf" TEXT,
  ADD COLUMN IF NOT EXISTS "escolaridade" TEXT,
  ADD COLUMN IF NOT EXISTS "pep" TEXT,
  ADD COLUMN IF NOT EXISTS "dependentes" INTEGER,
  ADD COLUMN IF NOT EXISTS "conjugeNome" TEXT,
  ADD COLUMN IF NOT EXISTS "conjugeCpf" TEXT,
  ADD COLUMN IF NOT EXISTS "conjugeDataNascimento" TIMESTAMP(3),
  ADD COLUMN IF NOT EXISTS "conjugeOcupacao" TEXT,
  ADD COLUMN IF NOT EXISTS "conjugeRenda" DECIMAL(14,2),
  ADD COLUMN IF NOT EXISTS "conjugeCelular" TEXT,
  ADD COLUMN IF NOT EXISTS "valorAluguel" DECIMAL(14,2),
  ADD COLUMN IF NOT EXISTS "dataAdmissao" TIMESTAMP(3),
  ADD COLUMN IF NOT EXISTS "comprovanteRenda" TEXT,
  ADD COLUMN IF NOT EXISTS "participacaoEmpresa" DECIMAL(5,2),
  ADD COLUMN IF NOT EXISTS "patrimonio" JSONB,
  ADD COLUMN IF NOT EXISTS "referenciasBancarias" JSONB,
  ADD COLUMN IF NOT EXISTS "inscricaoEstadual" TEXT,
  ADD COLUMN IF NOT EXISTS "naturezaJuridica" TEXT,
  ADD COLUMN IF NOT EXISTS "capitalSocial" DECIMAL(16,2),
  ADD COLUMN IF NOT EXISTS "faturamentoAnual" DECIMAL(16,2),
  ADD COLUMN IF NOT EXISTS "numeroFuncionarios" INTEGER,
  ADD COLUMN IF NOT EXISTS "referenciasComerciais" JSONB;
