export const ErrorCodes = {
  UNAUTHORIZED: 'UNAUTHORIZED',
  FILE_TOO_LARGE: 'FILE_TOO_LARGE',
  INVALID_MIME_TYPE: 'INVALID_MIME_TYPE',
  INVALID_HASH: 'INVALID_HASH',
  SESSION_NOT_FOUND: 'SESSION_NOT_FOUND',
  SESSION_EXPIRED: 'SESSION_EXPIRED',
  MAX_ATTEMPTS_REACHED: 'MAX_ATTEMPTS_REACHED',
  PASSWORD_PROTECTED_PDF: 'PASSWORD_PROTECTED_PDF',
  CORRUPTED_PDF: 'CORRUPTED_PDF',
  INVALID_PAYLOAD: 'INVALID_PAYLOAD',
  DUPLICATE_RESULT: 'DUPLICATE_RESULT',
} as const;
